# This is a basic workflow to help you get started with Actions

# Можно нажать Ctrl+Space авто выбор из списка

name: my-basic-GitHubActions   # имя без пробелов 

# глобальные переменные окружения
env:
  APPLICATION_NAME: "My_HelloWorld_GitHubActions"
  PACKAGE_NAME    : "Application-ver-${{ github.sha }}"  # sha commita

# Controls when the workflow will run  
# когда будет запускаться
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # [push, issues, issue_comment] # на любой push
  push:  # на push в ветку master
    branches: [ "master" ]
      # или - master
  pull_request:  # на pull request в ветку master
    branches: [ "master" ]
    

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: # каждый job запуститься на отдельной виртуальной машине (в докере)

  # This workflow contains job called "build"
  build:  # 1 job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Print message in build job, Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name:  Print message2 in build job, Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  
  my_testing: # 2 job
    runs-on: ubuntu-latest 
    needs: [build]   # по умолчанию все job запускаются одновременно, но если добавить блок needs, будут друг за другом
    steps:
      - name: Print message2 in my_testing job, Run a one-line script
        run: echo Hello, world 2!
        
#   my_deploy: # 3 job
  
